### ISSUE TITLE
Crash when trying to use filters on query.

### ISSUE THREAD

**Issue by aguxez** [kolorahl/blaze#1]
When you try to use filters (I only tried with `contains` and `in`, not sure about other options) on a query you'll get  function clause error because of the guard that's on the `field_filter/3` function. It's expecting the `field` arg to be a binary but an atom is being sent as it is a kw list. Not sure about all the parts of the library work but maybe we can change the guard clause or convert the `field` to a string before. I changed the guard clause to accept an atom instead of a string locally and I was able to perform queries. 

Refs: https://github.com/kolorahl/blaze/blob/master/lib/blaze/query.ex#L219 and https://github.com/kolorahl/blaze/blob/master/lib/blaze/query.ex#L193

BTW: Thanks for opening this up, looking forward to its development because the official lib is a pain in the ass.

**Comment by mcginleyr1** [comment]
I hit this same issue working on a new project and also trying out blaze instead of the official nest mess.  I hit it on a where like the example in the README.  Curious if you want to think out a bigger change for it or open to a PR that just makes the issue go away :)
